version: "3.9"

services:
  lvmh-rag:
    build: .
    container_name: lvmh-financial-rag
    ports:
      - "7860:7860"   # UI
      - "8000:8000"   # API
    env_file:
      - .env
    restart: unless-stopped
